---
- hosts: localhost
  connection: local
  vars:
    HOME: "{{lookup('env', 'HOME')}}"
    ARCHIVE: "{{HOME}}/Archive"

  tasks:

    - name: base directory
      file: path={{HOME}}/Archive/ state=directory

    - name: base application
      apt: name={{item}}
      sudo: yes
      with_items:
        - byobu
        - i3

    # emacs24 settings
    - name: emacs24 install
      apt: name=emacs24
      sudo: yes

    - name: generate .emacs.d/init.el
      template: src=templates/emacs24/init.el 
                dest={{HOME}}/.emacs.d/init.el

    # [TODO] atom install
    # .rbenv settings
    - name: apt get install for .rbenv dependencies
      apt: name={{item}}
      sudo: true
      with_items:
        - zlib1g-dev
        - build-essential
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libsqlite3-dev
        - sqlite3
        - libxml2-dev
        - libxslt1-dev
        - libcurl4-openssl-dev

    - name: git clone for .rbenv
      git: name=git://github.com/sstephenson/rbenv.git
           dest={{HOME}}/.rbenv

    - name: git clone for ruby-build
      git: name=git://github.com/sstephenson/ruby-build.git
           dest={{HOME}}/.rbenv/plugins/ruby-build

    # template generate
    - name: template generate for .bashrc
      template: src=templates/.bashrc.jinja2 dest={{HOME}}/.bashrc
