---
- hosts: localhost
  connection: local
  vars:
    HOME: "{{lookup('env', 'HOME')}}"
    ARCHIVE: "{{HOME}}/Archive"
    RUBY_VERSION: "2.1.4"

  tasks:

    - name: base directory
      file: path={{HOME}}/Archive/ state=directory
      
    - name: secret settings file touch
      file: path={{HOME}}/.secretrc state=touch

    - name: base application
      apt: name={{item}}
      sudo: yes
      with_items:
        - byobu
        - i3

    # install Ricty Font
    - name: generate .fonts
      file: path={{HOME}}/.fonts state=directory

    - name: FontForge install
      apt: name=fontforge
      sudo: yes

    - name: get Inconsolata.otf
      get_url: url=http://levien.com/type/myfonts/Inconsolata.otf
               dest={{HOME}}/.fonts/

    - name: clone repository for Ricky
      git: repo=https://github.com/yascentur/Ricty.git
           dest={{HOME}}/.fonts/ricty

    # Sorry, Completely not generate Ricky
    # You need access and get => http://mix-mplus-ipa.sourceforge.jp/migu/

    # emacs24 settings
    - name: emacs24 install
      apt: name=emacs24
      sudo: yes
 
    - name: generate .emacs.d/init.el
      template: src=templates/emacs24/init.el 
                dest={{HOME}}/.emacs.d/init.el

    # [TODO] atom install
    # .rbenv settings
    - name: apt get install for .rbenv dependencies
      apt: name={{item}}
      sudo: true
      with_items:
        - zlib1g-dev
        - build-essential
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libsqlite3-dev
        - sqlite3
        - libxml2-dev
        - libxslt1-dev
        - libcurl4-openssl-dev

    - name: git clone for .rbenv
      git: name=git://github.com/sstephenson/rbenv.git
           dest={{HOME}}/.rbenv

    - name: git clone for ruby-build
      git: name=git://github.com/sstephenson/ruby-build.git
           dest={{HOME}}/.rbenv/plugins/ruby-build
    
    - name: run rbenv install
      command: rbenv install {{RUBY_VERSION}}
      ignore_errors: yes
      
    - name: rbenv global setting
      command: rbenv global {{RUBY_VERSION}}

    - name: gem install
      gem: name=bundle state=latest

    # template generate
    - name: template generate for .bashrc
      template: src=templates/.bashrc.jinja2 dest={{HOME}}/.bashrc

    # [TODO] MySQL setup
    - name: mysql install
      apt: name={{item}} state=present
      sudo: true
      with_items:
        - mysql-client
        - mysql-server

    - name: mysql is running and enable
      service: name=mysql state=started enabled=yes
    
    # postgreSQL setup
    - name: postgresql install
      apt: name=postgresql state=present
      sudo: true